# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseClass',
            fields=[
                ('id', models.IntegerField(db_column='FId', primary_key=True, serialize=False)),
                ('student_id', models.CharField(max_length=100)),
                ('clazz_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('clazz', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='action.Clazz')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='clazz',
            name='teacher',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='action.User'),
        ),
    ]
