# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='action.Teacher')),
            ],
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.AddField(
            model_name='tree',
            name='clazz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trees', to='action.Clazz'),
        ),
    ]
